spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${EGSYS_DB_URL}
    username: ${EGSYS_DB_USERNAME}
    password: ${EGSYS_DB_PASSWORD}
  data:
    redis:
      host: ${EGSYS_REDIS_HOST}
      port: ${EGSYS_REDIS_PORT:6379}
      password: ${EGSYS_REDIS_PASSWORD}
      ssl:
        enabled: ${EGSYS_REDIS_SSL:true}
  jpa:
    hibernate:
      ddl-auto: validate

egsys:
  security:
    allowed-origins: ${EGSYS_ALLOWED_ORIGINS}
    password-pepper: ${EGSYS_PASSWORD_PEPPER}
    jwt:
      private-key: ${EGSYS_JWT_PRIVATE_KEY}
      public-key: ${EGSYS_JWT_PUBLIC_KEY}

logging:
  level:
    root: INFO
    br.com.egsys.tasks: INFO

management:
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN
  tracing:
    sampling:
      probability: ${EGSYS_TRACING_SAMPLE_PROBABILITY:0.1}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
