build:
  maxIssues: 0

config:
  validation: true

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120
  WildcardImport:
    active: true

complexity:
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 8

exceptions:
  TooGenericExceptionCaught:
    active: true
  TooGenericExceptionThrown:
    active: true

potential-bugs:
  UnsafeCallOnNullableType:
    active: true
